name: EduChat
description: Sistema de chat completo
main: net.eduard.chat.EduChat
version: ${project.version}
authors: [Eduard]
author: Eduard
depend: [EduardAPI]
website: https://www.youtube.com/user/EduTutoriaisHD
